### ISSUE TITLE
Admin Controls?

### ISSUE THREAD

**Issue by FormerlyChucks** [zezic/bordeaux#21]
It would be nice if admin controls were added

- Delete/remove posts and boards

- Ban users

**Comment by zezic** [comment]
@Mr-Steal-Your-Script I'm surprised that someone managed to find this repo and run the app at all :)
Regarding your wishes – I agree, would be nice to have such features. I can't say however, how soon I will be available to work on this project again.

**Comment by FormerlyChucks** [comment]
>I'm surprised that someone managed to find this repo and run the app at all

Its great code, still runs smooth, works just as intended, and I can easily read the code! Thanks for making this <3

>Regarding your wishes – I agree, would be nice to have such features.

I think it would be nice. For now, I can remove the files/data in the folder that correspond to the content that I'd want to remove.

>I can't say however, how soon I will be available to work on this project again.

I feel you. Times are tough now, but I hope you're doing great.
